"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths: BASE_DIR should be the root folder (where manage.py and .env live)
BASE_DIR = Path(__file__).resolve().parent.parent

# Load the env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# --- THE MISSING MAPPING ---
# Your .env uses WHATSAPP_TOKEN, but your views use WHATSAPP_ACCESS_TOKEN
# --- WhatsApp API Configuration ---
WHATSAPP_TOKEN = os.getenv("WHATSAPP_TOKEN")  # Add this line
WHATSAPP_ACCESS_TOKEN = WHATSAPP_TOKEN        # Keep this for backward compatibility
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_ID")
WHATSAPP_BUSINESS_ID = os.getenv("WHATSAPP_BUSINESS_ID")
VERIFY_TOKEN = os.getenv("VERIFY_TOKEN")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z1n)il=93)!$rna_!a%e+8^2m&qz1_n-vw*(+dscw7x+w(g178'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# core/settings.py
ALLOWED_HOSTS = ['mercato.rw', 'www.mercato.rw', '13.60.80.219', 'localhost', '127.0.0.1']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'escrow',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Locate the DATABASES section and update it:

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'solo_discovery',
        'USER': 'admin',
        'PASSWORD': 'Olivakarinda1@', # The one you set in Step 2
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/mercato/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# core/settings.py

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Add this section:
CSRF_TRUSTED_ORIGINS = [
    'https://mercato.rw',
    'https://www.mercato.rw'
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

