# Generated by Django 6.0.3 on 2026-03-04 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('monthly_fee_rwf', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(default='START', max_length=50)),
                ('temp_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('is_provider', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], max_length=20)),
                ('district', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('id_front', models.CharField(blank=True, max_length=255, null=True)),
                ('id_back', models.CharField(blank=True, max_length=255, null=True)),
                ('face_scan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rdb_cert_id', models.CharField(blank=True, max_length=255, null=True)),
                ('utility_bill_id', models.CharField(blank=True, max_length=255, null=True)),
                ('portfolio_images', models.JSONField(default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('trust_score', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escrow.categoryconfig')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='escrow.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_phone', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='escrow.provider')),
            ],
        ),
    ]
