# Generated by Django 6.0.3 on 2026-03-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryconfig',
            name='monthly_fee_rwf',
        ),
        migrations.AddField(
            model_name='categoryconfig',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoryconfig',
            name='min_flat_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='categoryconfig',
            name='percentage_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='categoryconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
