# Generated by Django 6.0.3 on 2026-03-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_remove_categoryconfig_monthly_fee_rwf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='face_scan_id',
            new_name='face_scan',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='rdb_cert_id',
            new_name='rdb_doc',
        ),
        migrations.RemoveField(
            model_name='categoryconfig',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categoryconfig',
            name='min_flat_fee',
        ),
        migrations.RemoveField(
            model_name='categoryconfig',
            name='percentage_fee',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='name',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='utility_bill_id',
        ),
        migrations.AddField(
            model_name='categoryconfig',
            name='monthly_fee_rwf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='business_name',
            field=models.CharField(default='Pending Name', max_length=255),
            preserve_default=False,
        ),
    ]
