# Generated by Django 6.0.3 on 2026-03-07 12:21

import escrow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0003_rename_face_scan_id_provider_face_scan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='face_scan',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[escrow.models.validate_video_length]),
        ),
    ]
