# Generated by Django 6.0.3 on 2026-03-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0004_alter_provider_face_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryconfig',
            name='group',
            field=models.CharField(db_index=True, default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='categoryconfig',
            name='icon',
            field=models.CharField(default='🛠️', max_length=10),
        ),
    ]
