# Generated by Django 6.0.3 on 2026-03-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0005_categoryconfig_group_categoryconfig_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete to free up phone number for new service'),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Allows provider to hide/show themselves in search'),
        ),
        migrations.AddField(
            model_name='provider',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
