# Generated by Django 6.0.3 on 2026-03-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0006_provider_is_deleted_provider_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
