# Generated by Django 6.0.3 on 2026-03-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0007_alter_provider_payment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=50, unique=True, verbose_name='Transaction ID')),
                ('amount', models.IntegerField(verbose_name='Amount Received')),
                ('payer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_text', models.TextField(help_text='The original SMS content')),
                ('is_used', models.BooleanField(default=False, help_text='Checked if a provider has already claimed this money')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MoMo Bank Record',
                'ordering': ['-created_at'],
            },
        ),
    ]
